### ISSUE TITLE
Python quick start code

### ISSUE THREAD

**Issue by DePasqualeOrg** [JosefAlbers/e2tts-mlx#1]
I'd love to dig into this. Could you provide an example in Python to run the pre-trained model in a notebook? Also, I noticed that the generated audio with the pre-trained model has a lot of background noise. Is this expected, and is there a way to mitigate it?

**Comment by nattaylor** [comment]
I also got lots of noise - example here https://nattaylor.com/labs/tts_0.wav

v0.0.3
python3.12.3
m1 pro v15.0.1

Thank you for putting together the package!  I'm looking forward to taking it for a spin.

**Comment by JosefAlbers** [comment]
@DePasqualeOrg:

Thanks for giving my code a try! You're right that a notebook example would be helpful. For now, here's a quick Python snippet to get you started with running the pretrained model (which is actually just a tiny model trained on no more than a handful of <4 second audio clips and was uploaded only for demo purpose):

```python
from e2tts_mlx import tts
tts("From now on we're pals.")
```

Or if you've installed via pip, you can use the CLI:

```bash
e2tts 'Now, you understand.'
```

I'll work on a more comprehensive Jupyter notebook at some point later. Let me know if you have specific areas you'd like covered.

@nattaylor:

Thanks for the feedback and sharing the example! The noise is related to some ad hoc adjustments in the code I made to simplify and streamline the training process. I may refactor some of these over the upcoming weekend, and it would be great if you could take another look once I've made the changes.

**Comment by DePasqualeOrg** [comment]
Thanks! The examples from the original paper were very impressive, so I'm looking forward to trying this out.

**Comment by JosefAlbers** [comment]
The [examples](https://www.microsoft.com/en-us/research/project/e2-tts/) are what hooked me in too!
